// <auto-generated />
using CRUDAspNetCoreMVCWebAppComEFCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUDAspNetCoreMVCWebAppComEFCore.Migrations
{
    [DbContext(typeof(EmpregadosContext))]
    [Migration("20210212010207_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUDAspNetCoreMVCWebAppComEFCore.Models.Empregados", b =>
                {
                    b.Property<int>("EmpregadosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Funcao")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LocalizacaoEscritorio")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("EmpregadosId");

                    b.ToTable("Empregados");
                });
#pragma warning restore 612, 618
        }
    }
}
